# big.ps1 - deliberately exceeds the 4096-byte drilldown size cap (deterministic padding).
# padding line 001 - this file is too large to inspect by the drilldown engine
# padding line 002 - this file is too large to inspect by the drilldown engine
# padding line 003 - this file is too large to inspect by the drilldown engine
# padding line 004 - this file is too large to inspect by the drilldown engine
# padding line 005 - this file is too large to inspect by the drilldown engine
# padding line 006 - this file is too large to inspect by the drilldown engine
# padding line 007 - this file is too large to inspect by the drilldown engine
# padding line 008 - this file is too large to inspect by the drilldown engine
# padding line 009 - this file is too large to inspect by the drilldown engine
# padding line 010 - this file is too large to inspect by the drilldown engine
# padding line 011 - this file is too large to inspect by the drilldown engine
# padding line 012 - this file is too large to inspect by the drilldown engine
# padding line 013 - this file is too large to inspect by the drilldown engine
# padding line 014 - this file is too large to inspect by the drilldown engine
# padding line 015 - this file is too large to inspect by the drilldown engine
# padding line 016 - this file is too large to inspect by the drilldown engine
# padding line 017 - this file is too large to inspect by the drilldown engine
# padding line 018 - this file is too large to inspect by the drilldown engine
# padding line 019 - this file is too large to inspect by the drilldown engine
# padding line 020 - this file is too large to inspect by the drilldown engine
# padding line 021 - this file is too large to inspect by the drilldown engine
# padding line 022 - this file is too large to inspect by the drilldown engine
# padding line 023 - this file is too large to inspect by the drilldown engine
# padding line 024 - this file is too large to inspect by the drilldown engine
# padding line 025 - this file is too large to inspect by the drilldown engine
# padding line 026 - this file is too large to inspect by the drilldown engine
# padding line 027 - this file is too large to inspect by the drilldown engine
# padding line 028 - this file is too large to inspect by the drilldown engine
# padding line 029 - this file is too large to inspect by the drilldown engine
# padding line 030 - this file is too large to inspect by the drilldown engine
# padding line 031 - this file is too large to inspect by the drilldown engine
# padding line 032 - this file is too large to inspect by the drilldown engine
# padding line 033 - this file is too large to inspect by the drilldown engine
# padding line 034 - this file is too large to inspect by the drilldown engine
# padding line 035 - this file is too large to inspect by the drilldown engine
# padding line 036 - this file is too large to inspect by the drilldown engine
# padding line 037 - this file is too large to inspect by the drilldown engine
# padding line 038 - this file is too large to inspect by the drilldown engine
# padding line 039 - this file is too large to inspect by the drilldown engine
# padding line 040 - this file is too large to inspect by the drilldown engine
# padding line 041 - this file is too large to inspect by the drilldown engine
# padding line 042 - this file is too large to inspect by the drilldown engine
# padding line 043 - this file is too large to inspect by the drilldown engine
# padding line 044 - this file is too large to inspect by the drilldown engine
# padding line 045 - this file is too large to inspect by the drilldown engine
# padding line 046 - this file is too large to inspect by the drilldown engine
# padding line 047 - this file is too large to inspect by the drilldown engine
# padding line 048 - this file is too large to inspect by the drilldown engine
# padding line 049 - this file is too large to inspect by the drilldown engine
# padding line 050 - this file is too large to inspect by the drilldown engine
# padding line 051 - this file is too large to inspect by the drilldown engine
# padding line 052 - this file is too large to inspect by the drilldown engine
# padding line 053 - this file is too large to inspect by the drilldown engine
# padding line 054 - this file is too large to inspect by the drilldown engine
# padding line 055 - this file is too large to inspect by the drilldown engine
# padding line 056 - this file is too large to inspect by the drilldown engine
# padding line 057 - this file is too large to inspect by the drilldown engine
# padding line 058 - this file is too large to inspect by the drilldown engine
# padding line 059 - this file is too large to inspect by the drilldown engine
# padding line 060 - this file is too large to inspect by the drilldown engine
# padding line 061 - this file is too large to inspect by the drilldown engine
# padding line 062 - this file is too large to inspect by the drilldown engine
# padding line 063 - this file is too large to inspect by the drilldown engine
# padding line 064 - this file is too large to inspect by the drilldown engine
# padding line 065 - this file is too large to inspect by the drilldown engine
# padding line 066 - this file is too large to inspect by the drilldown engine
# padding line 067 - this file is too large to inspect by the drilldown engine
# padding line 068 - this file is too large to inspect by the drilldown engine
# padding line 069 - this file is too large to inspect by the drilldown engine
# padding line 070 - this file is too large to inspect by the drilldown engine
# padding line 071 - this file is too large to inspect by the drilldown engine
# padding line 072 - this file is too large to inspect by the drilldown engine
# padding line 073 - this file is too large to inspect by the drilldown engine
# padding line 074 - this file is too large to inspect by the drilldown engine
# padding line 075 - this file is too large to inspect by the drilldown engine
# padding line 076 - this file is too large to inspect by the drilldown engine
# padding line 077 - this file is too large to inspect by the drilldown engine
# padding line 078 - this file is too large to inspect by the drilldown engine
# padding line 079 - this file is too large to inspect by the drilldown engine
# padding line 080 - this file is too large to inspect by the drilldown engine
# padding line 081 - this file is too large to inspect by the drilldown engine
# padding line 082 - this file is too large to inspect by the drilldown engine
# padding line 083 - this file is too large to inspect by the drilldown engine
# padding line 084 - this file is too large to inspect by the drilldown engine
# padding line 085 - this file is too large to inspect by the drilldown engine
